logging:
  config: 'classpath:log4j2.yml'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: postgres
    password: 1337
    driver-class-name: org.postgresql.Driver